---

- name: Launche AWS ec2 instance
  hosts: localhost
  gather_facts: False

  vars:
    key_name: my_aws             # Key used for SSH
    region: us-east-1
    image: ami-0fe630eb857a6ec83
    id: "example testing"
    instance_type: t2.micro
    # vpc_id: subnet-012345
    sec_group: "test-security-group"
    ec2_access_key: AKIA435SZYLREADGi7
    ec2_secret_key: aGlIAqc3/atrtajaRwZRX3BatjvrFWP31t0T67sf

  tasks:
    - name: Provisioning EC2 instances
      block:

      - name: Create security group
        amazon.aws.ec2_security_group:
          name: "{{ sec_group }}"
          description: "Sec group for app"
          region: "{{ region }}"
          aws_access_key: "{{ec2_access_key}}"
          aws_secret_key: "{{ec2_secret_key}}"
          rules:                                # allows ssh on port 22
            - proto: tcp
              ports:
                - 22
              cidr_ip: 0.0.0.0/0
              rule_desc: allow all on ssh port

      - name: Amazon EC2 | Create Key Pair      # Create key pair for ssh
        amazon.aws.ec2_key:
          name: "{{ key_name }}"
          region: "{{ region }}"
          aws_access_key: "{{ec2_access_key}}"
          aws_secret_key: "{{ec2_secret_key}}"
          key_material: "{{ item }}"
        with_file: /root/.ssh/my_aws.pub

      - name: Start an instance with a public IP address   # Inastance NAME
        amazon.aws.ec2_instance:
          name: "test"
          key_name: "{{ key_name }}"
          # vpc_subnet_id: "{{ vpc_id }}"
          instance_type: "{{ instance_type }}"
          security_group: "{{ sec_group }}"
          aws_access_key: "{{ ec2_access_key }}"
          aws_secret_key: "{{ ec2_secret_key }}"
          region: "{{ region }}"
          network:
            assign_public_ip: true
          image_id: "{{ image }}"


    - name: Facts
      block: # this block prints out instance data

      - name: Get instances facts
        amazon.aws.ec2_instance_info:
          aws_access_key: "{{ ec2_access_key }}"
          aws_secret_key: "{{ ec2_secret_key }}"
          region: "{{ region }}"
        register: result

      - name: Instances ID
        debug:
          msg: "ID: {{ item.instance_id }} - State: {{ item.state.name }} - Public DNS: {{ item.public_dns_name }}"
        loop: "{{ result.instances }}"

       

